# alertmanager.yml
global:
  resolve_timeout: 5m

# The root route configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-receiver'
      repeat_interval: 5m
    - match:
        severity: warning
      receiver: 'warning-receiver'
      repeat_interval: 15m
    - match:
        alertname: InstanceDown
      receiver: 'critical-receiver'
      repeat_interval: 2m

# Receivers configuration
receivers:
  - name: 'default-receiver'
    webhook_configs:
      - url: '${webhook_url}'
        send_resolved: true
        http_config:
          follow_redirects: true
        title: 'Prometheus Alert'

  - name: 'critical-receiver'
    webhook_configs:
      - url: '${webhook_url}'
        send_resolved: true
        http_config:
          follow_redirects: true
        title: 'CRITICAL: Prometheus Alert'

  - name: 'warning-receiver'
    webhook_configs:
      - url: '${webhook_url}'
        send_resolved: true
        http_config:
          follow_redirects: true
        title: 'WARNING: Prometheus Alert'

# Inhibit rules to suppress alerts
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
  
  - source_match:
      severity: 'warning'
    target_match:
      severity: 'info'
    equal: ['alertname', 'cluster', 'service']

  # Inhibit HighCPU when InstanceDown
  - source_match:
      alertname: 'InstanceDown'
    target_match_re:
      alertname: 'High.*Usage'
    equal: ['instance']