alertmanager_config: |
  global:
    resolve_timeout: 5m
  
  route:
    group_by: ['alertname']
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 12h
    receiver: 'sns-webhook'
  
  receivers:
  - name: 'sns-webhook'
    sns_configs:
    - topic_arn: '${sns_topic_arn}'
      sigv4:
        region: '${aws_region}'
      subject: 'Prometheus Alert'
